### ISSUE TITLE
Blocked channels show after refreshing the page

### ISSUE THREAD

**Issue by uBumeister** [LinogeFly/hide-unwanted-streams-on-twitch#19] opened 2017-08-16 09:54 UTC
the issue is relatively new. if i block a channel it is hidden but after refreshing the page (F5) it will show again.
after another resfresh its hidden again... and so on

**Comment by LinogeFly** [comment] 2017-08-16 10:04
Could you please do following for me to get better understadning of the problem?
1) Block a channel (don't refresh the page after that)
2) Press F12 in Chrome
3) Switch to Console tab
4) Make a screenshot and post it somewhere (e.g. http://imgur.com). Also, make a full browser window screenshot so I can see the URL. Screenshot should look something like this: http://i.imgur.com/VHQ7VhF.png.

**Comment by uBumeister** [comment] 2017-08-17 16:11
thx for the quick answer. 
link to screenshot: http://imgur.com/a/vD6Ym
idk why but now it works fine. is there a limit for blocked channels? i had like 100+ blocked channels and yesterday unblocked all except  a handful of the most annoying.

best regards
uBu

**Comment by LinogeFly** [comment] 2017-08-17 19:44
Oh, so you are using Firefox. Then there shouldn't be any limit for blocked items (games or channels) if I'm not mistaken. Because for Chrome there is a limit as settings are stored in Chrome profile and there is a size limit for settings per extension. Roughly about 2000-3000 items can be blocked in Chrome. After limit is reached it behaves exactly as you described (streams become visible after you refresh the page). But since you are using Firefox... I don't know what might be the issue. Perhaps Greasemonkey has some sort of limit as well, not sure yet.

**Comment by Remadan** [comment] 2017-09-06 09:33
I have the same issue on Firefiox 52.2.0
Here is 2 tabs open at the same time: http://i.imgur.com/XB2v2IT.png
Seems like channel and game filtering is not happening in around 70% of the time. If i keep pressing refresh button - blocked channels will eventually disappear.
While filtering itself is not working, HUSOT seems to be active. I can still block a channel or edit settings.

**Comment by LinogeFly** [comment] 2017-09-06 11:43
Thanks. Yeah, I can reproduce the problem also. I will look into it soon.

**Comment by LinogeFly** [comment] 2017-09-22 16:37
This problem should be now fixed.

**Closed by LinogeFly** 2017-09-22 16:37 UTC
